version: ' 3.8

services:
  backend:
    build: .
    ports:
      - '8000:80'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build: ./ui
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000